### ISSUE TITLE
PHP 8.0 - ready?

### ISSUE THREAD

**Issue by kakojak** [mehradsadeghi/laravel-filter-querystring#1]
Hello,

what about php 8.0? Is it ready for it?
Could you update the composer requirements?

Thanks

**Comment by mehradsadeghi** [comment]
Hello @kakojak 
I hope you're doing well.

I'll get to it as soon as possible.

**Comment by kakojak** [comment]
Thanks. Because its looks great to use.

**Comment by mehradsadeghi** [comment]
Hello again @kakojak 

I added the support for PHP 8. You need to download the `v1.1.5` of the package.
I would appreciate if you test it and report any issue if existed.
