### ISSUE TITLE
Question: adding core filters to custom filters

### ISSUE THREAD

**Issue by seewhy17** [mehradsadeghi/laravel-filter-querystring#12]
I have this situation where I have custom filters:
```
...
    protected $filters = [
        'buyers_name',
        'product_name',
        'product_condition',
        'sold_at',
    ];
```
all of which depend on some relationship.
How do I add core filters on these custom filters, say 'sort' and 'between' on sold-at(remember ```sold_at``` is not a column but a custom filter to access a relationship)

**Comment by mehradsadeghi** [comment]
Dear @seewhy17 at the moment this is not possible and you need to do these filtering inside the custom filter.
