### ISSUE TITLE
Partially override default filters

### ISSUE THREAD

**Issue by morfin** [mehradsadeghi/laravel-filter-querystring#13]
Hi,

It'd be great to be able to do something like this:

```
protected $filters = [less', 'less:age'];

public function less_age($query, $value) {
...
}
```

As you can notice, instead of overriding the whole "less" filter, we just override it when the property "age" is provided:
?less=age,20

In such case, "less" on its own will work for most cases, but also we can apply custom functionality for certain provided properties.

Thanks.

**Comment by mehradsadeghi** [comment]
Hi dear @morfin .  It would be a nice feature. I'd appreciate any PR regarding this feature.
