### ISSUE TITLE
Exception: Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by fivaz** [mehradsadeghi/laravel-filter-querystring#2]
Do you use ReflectionParameter::getClass() in your FilterQueryString or somewhere else in your code? I get this error when I try to generate IDE helper for Laravel on Modules that use FilterQueryString. 

i'm  generating the IDE helper with this repository https://github.com/barryvdh/laravel-ide-helper

![image](https://user-images.githubusercontent.com/31249205/109489903-ce955980-7a87-11eb-9d68-8c0776471b72.png)

**Comment by mehradsadeghi** [comment]
Hello @fivaz .
I haven't used any reflection in my code. 
I don't see any error regarding my package in your screenshot.
Are you sure this error is because of my package ?
