### ISSUE TITLE
pivot (multi filter)

### ISSUE THREAD

**Issue by XairoYazan** [mehradsadeghi/laravel-filter-querystring#21]
public function items()
    {
        return $this->belongsToMany(Item::class, 'product_item');
    }

    public function fieldus()
    {
        return $this->belongsToMany(Fieldus::class, 'product_fielduse');
    }

    public function materials()
    {
        return $this->belongsToMany(Material::class, 'product_material','product_id','material_id');
    }

    protected $filters = ['item_filter','fieldus','materials'];

    public function item_filter($query, $value)
    {

    }

hello i am new in laravel and would like to ask how can i make a filter with pivot

**Comment by mehradsadeghi** [comment]
I believe there are lots of resources for this issue out there. [Laravel's docs](https://laravel.com/docs/9.x/eloquent-relationships) is the first choice I geuss.
