### ISSUE TITLE
Error in Mehradsadeghi\FilterQueryString\Filters\ComparisonClauses\BaseComparison

### ISSUE THREAD

**Issue by validiom** [mehradsadeghi/laravel-filter-querystring#23]
Hi, hope you're going well.

I got an anomaly in code behavior in `BaseComparision`'s `determineMethod()` method.
I think the problem came with the use use of `isDateTime()` function in Helpers. That function miss-parse the date and consider the some integer as a date.
In this error <code>"SQL: select count(*) as aggregate from `expenses` where date(`amount`) >= 9999)"</code>, the column `amount` isn't date but is considered as one.
I suggest you test if value is int and return the int value otherwise check if value is date and act so.

I hope I explain the issue well. Thanks.

**Comment by mehradsadeghi** [comment]
Hi. Thanks for your attention.

If we prevent `int` type for `date`, we're ignoring those who are using unix timestamp as `date time` for the type of their column.

In these scenarios I guess validating the input (to whatever we need) before it reaches the database query would be a better idea.

**Comment by validiom** [comment]
I guess. To simplify, you can use the "dates" array property that lists all
date column in a Model.

**Comment by validiom** [comment]
And for each comparison, check if the given column is in the dates array
before selecting the "where" Ou "whereDate" clause.

I think it's a bit cleaner to proceed that way.

**Comment by validiom** [comment]
While your are looking for a solution, could you give me a clean and simple
way to modify this behavior of your package without touching the vendor?
Please.

**Comment by mehradsadeghi** [comment]
I'll close this issue since I haven't heard from you anymore. If you had any question, hit another reply.

**Comment by validiom** [comment]
Hi, 🙏🏽
i'm so soooorry Mehra. I was busy for a moment.

I'm okay with that.

Here is a screenshot of the code in laravel Model trait `hasAttributes`. I
didn't found a documentation about it, even in the official laravel web
sites. Maybe I'm not a good researcher!😁
[image: image.png]

For defining custom filters, it's right and works for me. But I think it is
not suitable to always define custom code for a "native" functionality.

Take a look at my code
[image: image.png]

I'll be forced to bring this trait in All my projects.

I hope a little modification will help make a more efficient use of the
package and that you'll work for.
If you don't have time, just tell me, I'll make the modifications you want.
I'm a lover of your package and want it to stay easy to use.

Thanks for everything and sorry one more time.

Le dim. 28 juil. 2024 à 05:03, Mehrad Sadeghi ***@***.***> a
écrit :
