### ISSUE TITLE
Unknown columns problem

### ISSUE THREAD

**Issue by th3m1n1c0d34** [mehradsadeghi/laravel-filter-querystring#3]
Hey !
Thanks for the great package !
I would like to cite this little problem, When sending this request for example:
`http://localhost:8000/api/items?like=aColumn,5`
And the `aColumn` doesn't exist, it throws an error
` SQLSTATE[42S22]: Column not found: 1054 Unknown column 'aColumn' in 'where clause' (SQL: select count(*) as aggregate from items where (aColumn like %5%)) `
It would be way better to filter the columns names before using them !

**Comment by mehradsadeghi** [comment]
Hello @th3m1n1c0d34 
I hope you're doing well and thanks for using my package.

I think your suggestion is not a bad idea, But I see more benefit in letting the client (a developer like yourself) to handle these kind of exceptions by him/her self.

Assume a situation that the client needs to handle (e.g. log) the request when end-user is requesting a database column that doesn't exists, For security reasons.
