### ISSUE TITLE
[Feature request] Add the posibility to select the columns that can be used with an 'in'-filter for instance

### ISSUE THREAD

**Issue by madman-81** [mehradsadeghi/laravel-filter-querystring#5]
Right now you can select the filters that you want to offer like this:
```
protected $filters = ['in'];
```

Or you can select the columns that the default 'where' filter can use:
```
protected $filters = ['name', 'username', 'age'];
```
But it's not possible to combine the two: 
```
protected $filters = [
    'in',
    'name', 'age'
];
```

This filter will not allow you to use the query 
```
https://example.com?age=22&username=dariush123
```
But this works:
```
https://example.com?age=22&in=username,dariush123
```

A possible solution could be to split the two lists like this:

```
protected $filters = ['in','where'];
protected $filter_columns = ['name', 'age'];
```

The advantage is that the developer has more control over the 'exposed' columns and also more control over the enable filters.

**Comment by mehradsadeghi** [comment]
Hello @madman-81 
I believe filters work fine the way you described above (or maybe I didn't understand the issue correctly).
About exposing columns as I described in readme file, It is possible to create custom functions to wrap a column and prevent exposing the real name of that column.

**Comment by madman-81** [comment]
Is it possible to select which columns can be used in the "in" filter? Maybe I did something wrong, but I was able to filter on a column that wasn't specified in the $filter array. See my example: you can filter on the column "username", but it isn't in the filter list.

In my opinion this is a security risk because it allows attackers to determine you database model and allow them to find out values for columns that are normally not exposed. You could use this for example on the password column as well, or the is_admin_user column (if you would have one).

**Comment by mehradsadeghi** [comment]
Yes there is a solution for this available [here](https://github.com/mehradsadeghi/laravel-filter-querystring#custom-filters).
You can override your custom `in` with the default one in order to prevent from exposing all columns.
Please take a look at [custom filters](https://github.com/mehradsadeghi/laravel-filter-querystring#custom-filters).
