### ISSUE TITLE
How can I defined a default sort to be applied if no sort is provided via URL query?

### ISSUE THREAD

**Issue by morfin** [mehradsadeghi/laravel-filter-querystring#6]
It'll be great to be able to define in the model a default column and sort type  (ASC/DESC) to be applied if no sort parameters are provided on the request.

Meanwhile, what do you suggest to achieve such thing?

**Comment by mehradsadeghi** [comment]
You can do this in different ways like using laravel `global scopes` and etc. Take a look at different solutions mentioned [here](https://stackoverflow.com/questions/20701216/laravel-default-orderby).
